### ISSUE TITLE
A question about loss design

### ISSUE THREAD

**Issue by hanquansanren** [gwxie/Document-Dewarping-with-Control-Points#17]
最近看了您的文章《document dewarping with control points》的开源代码，非常感谢您无私的开源工作。我关注到您的loss部分使用了Smooth L1 loss以及微分坐标的loss，这是和原文一致的。同时，我也主要到您的开源代码中同时也提供了edge loss和cross line loss， rectangle loss。请问您有试验过，加上这几种loss可以涨点吗？我的直觉想法也是edge部分的point可能会更加重要，但是没有进行过试验。

![image](https://user-images.githubusercontent.com/36793626/194562615-3fadfbf1-7169-4b4c-bb6c-ab36ac3e95c2.png)

另外，文章中的图5中提到了设置超参数neighbor vertices k=5和k=17。我想问一下你有没有尝试过其他的k，k是否越大越好呢？

非常期待你的回复！

**Comment by gwxie** [comment]
> 最近看了您的文章《document dewarping with control points》的开源代码，非常感谢您无私的开源工作。我关注到您的loss部分使用了Smooth L1 loss以及微分坐标的loss，这是和原文一致的。同时，我也主要到您的开源代码中同时也提供了edge loss和cross line loss， rectangle loss。请问您有试验过，加上这几种loss可以涨点吗？我的直觉想法也是edge部分的point可能会更加重要，但是没有进行过试验。
> 
> ![image](https://user-images.githubusercontent.com/36793626/194562615-3fadfbf1-7169-4b4c-bb6c-ab36ac3e95c2.png)
> 
> 另外，文章中的图5中提到了设置超参数neighbor vertices k=5和k=17。我想问一下你有没有尝试过其他的k，k是否越大越好呢？
> 
> 非常期待你的回复！

你好
提到的这些需要调惨实验。
加上这几种loss会有效，只用文中的loss也可达到类似效果。
可能会越大越好，没有做太多这方面消融实验，

**Comment by hanquansanren** [comment]
好的，感谢您的反馈
