### ISSUE TITLE
下载model parameters的那个网盘地址打不开了

### ISSUE THREAD

**Issue by libin47** [gwxie/Document-Dewarping-with-Control-Points#4]

**Comment by gwxie** [comment]
Google：  https://drive.google.com/file/d/1rKS03wHMoAXp8uR1h3z7NAVoBY84NZlp/view?usp=sharing

Baidu:   https://pan.baidu.com/s/1eSoiE3LoSQmTIL-SpbzPRw?pwd=rngi       password: rngi
