### ISSUE TITLE
python test.py报错

### ISSUE THREAD

**Issue by fanghaiquan1** [gwxie/Document-Dewarping-with-Control-Points#8]
python test.py

Traceback (most recent call last):
  File "test.py", line 183, in <module>
    train(args)
  File "test.py", line 41, in train
    _re_date = re_date.search(args.resume.name).group(0)
AttributeError: 'str' object has no attribute 'name'

**Comment by gwxie** [comment]
> python test.py
> 
> Traceback (most recent call last): File "test.py", line 183, in train(args) File "test.py", line 41, in train _re_date = re_date.search(args.resume.name).group(0) AttributeError: 'str' object has no attribute 'name'

Bug fixes.

 May 4, 2022

**Comment by fanghaiquan1** [comment]
您好！您的这个程序非常好。可以加微信讨论吗？用的过程中发现了个小问题。
矫正之后的图片分辨率降低了很多，如何调整参数？矫正后的图片不失真。
另外，目前发现矫正后的文字发生变形，有时变得扁平，有时变瘦长，能否做到不变形？谢谢！


方海泉
浙江工业大学
13661043522




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gwxie/Document-Dewarping-with-Control-Points"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月4日(星期三) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gwxie/Document-Dewarping-with-Control-Points] python test.py报错 (Issue #8)





  
python test.py
 
Traceback (most recent call last): File "test.py", line 183, in train(args) File "test.py", line 41, in train _re_date = re_date.search(args.resume.name).group(0) AttributeError: 'str' object has no attribute 'name'
  
Bug fixes.
 
May 4, 2022

**Comment by fourierer** [comment]
> 

hello，请问你解决图像分辨率下降这个问题了么，我这边也是遇到相同的情况

**Comment by fourierer** [comment]
> 您好！您的这个程序非常好。可以加微信讨论吗？用的过程中发现了个小问题。 矫正之后的图片分辨率降低了很多，如何调整参数？矫正后的图片不失真。 另外，目前发现矫正后的文字发生变形，有时变得扁平，有时变瘦长，能否做到不变形？谢谢！ 方海泉 浙江工业大学 13661043522
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gwxie/Document-Dewarping-with-Control-Points" ***@***.***&gt;; 发送时间:&nbsp;2022年5月4日(星期三) 下午2:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gwxie/Document-Dewarping-with-Control-Points] python test.py报错 (Issue #8) python test.py Traceback (most recent call last): File "test.py", line 183, in train(args) File "test.py", line 41, in train _re_date = re_date.search(args.resume.name).group(0) AttributeError: 'str' object has no attribute 'name' Bug fixes. May 4, 2022 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

hello，请问你解决图像分辨率下降这个问题了么，我这边也是遇到相同的情况
